### ISSUE TITLE
add support for mkNumeral in Z3Wrapper and Z3Contex, and everything Real related

### ISSUE THREAD

**Issue by anterak13** [epfl-lara/ScalaZ3#13]
Add a method mkNumeral(String, Sort) in the Z3Context to be able to create arbitrary precision integers and real numbers based on their string representation (reals are written as rational fractions with arbitrary precision integers as numerators and denominators). Current state of the Z3Context only allows Int constants and  and fractions of integers for Real constants.

Also, add support for get methods for numeral values of Real sort, especially those which return string representations.

**Comment by romac** [comment]
I think we can close this as support was added in ca62ad2d.
