### ISSUE TITLE
GCC 5 uses the GNU11 standard, which breaks how inline functions are used.

### ISSUE THREAD

**Issue by koksal** [epfl-lara/ScalaZ3#48]
I'm on OS X, and the C compilation fails when GCC 5 is used. I tracked down the cause to the change of standard from GNU89 to GNU11, affecting the semantics of inline functions. 

A quick "fix" is to pass the flag `-std=gnu89` to GCC. I assume the alternative is to rename inline functions to "extern inline" ones, which should be equivalent to the old "inline" functions in C99 semantics  that are used now by default (according to [this document](https://gcc.gnu.org/gcc-5/porting_to.html)).

**Comment by colder** [comment]
For now I added -std=gnu89. 

If somebody has some time of their hands, feel free to revisit this and fix the code to work on gnu11.

Best,
