### ISSUE TITLE
Implement `*ValHandler.convert(...)` directly in `ValHandler` 

### ISSUE THREAD

**Issue by ptitjes** [epfl-lara/ScalaZ3#53]
It seems to me that implementing `convert(...)` in every `ValHandler` subclasses defeats the purpose of the `Default` type-class.

I'm willing to make a PR for this.

**Comment by samarion** [comment]
I think `Default` and `convert(...)` are somewhat different (see Philippe's comments in ValHandler.scala on why). However, I think we could indeed replace `convert` by something that returns an option and use the `defaultValue` as a getOrElse to reduce duplication.

Please open a PR if you want this changed :)

**Comment by ptitjes** [comment]
Well, I tried to implement it without success. Scala's implicit handling impose that the implicit resolution of the converter occurs where the type is fully know (hence in `ValHandler`'s subclass...).
Closing.
