### ISSUE TITLE
Cannot find checkAndGetAllModels

### ISSUE THREAD

**Issue by pdmatei** [epfl-lara/ScalaZ3#83]
Hello,
I am trying to replicate some examples seen online and I cannot find checkAndGetAllModels or an equivalent way to iterate over all models produced by a solver.
Is this still supported in the current version?
Can you help me out with trying to iterate over all possible models of a set of constraints?

Thank you in advance!

**Comment by mario-bucev** [comment]
Hello,
The function is [still here](https://github.com/epfl-lara/ScalaZ3/blob/cece333d5310897e626691dbbe63fd89ede05059/src/main/scala/z3/scala/Z3Solver.scala#L107) but for some reasons it is private. I'll push a change to make it public and will notify you :)

**Comment by mario-bucev** [comment]
It's merged! If you need anything else, I'd be happy to answer any further question. As I'm not the original author of ScalaZ3, I'll try to do my best :)

**Comment by pdmatei** [comment]
Thank you so much! You really saved my project!
