### ISSUE TITLE
`Arrays` test fails with later versions of Z3

### ISSUE THREAD

**Issue by psuter** [epfl-lara/ScalaZ3#9]
It's all in the title.

We should look into the representation of models of arrays, including functions to access default values etc.

**Comment by romac** [comment]
Arrays tests are now passing with Z3 4.7.1

**Comment by romac** [comment]
@psuter Fun fact: that was apparently your first GitHub issue ever ;)

<img width="409" alt="Screenshot 2019-06-18 at 17 08 00" src="https://user-images.githubusercontent.com/106849/59696096-a4383580-91eb-11e9-8595-ea2929f67ac7.png">
